version: "3.7"


services:
    database:
        image: postgres
        container_name: database_manga_scrapping
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - pgdata:/data/postgres


    cache_manager:
        container_name: api_redis_cache_maneger
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        volumes:
            - redisdata:/data/redis

    app:
        container_name: app_api
        build: .
        ports:
            - ${API_PORT}:${API_PORT}
        volumes:
            - .:/home/service
        depends_on:
            - database
            - cache_manager


volumes:
    pgdata:
    redisdata:
